### ISSUE TITLE
Error: Cannot find module './bin/index'

### ISSUE THREAD

**Issue by poorpaper** [bsorrentino/extract-pdf-images#5]
I really appreciate this project, but when I finish the installation, using the `pdftools pdf2md` command shows the error `Error: Cannot find module '. /bin/index'`
in detail:
```
Error: Cannot find module './bin/index'
Require stack:
- E:\pdf-tools-1.0.1\pdf-tools-1.0.1\cli.js
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)[39m
[90m    at require (node:internal/modules/cjs/helpers:102:18)[39m
    at Object.<anonymous> (E:\pdf-tools-1.0.1\pdf-tools-1.0.1\cli.js:3:14)
[90m    at Module._compile (node:internal/modules/cjs/loader:1105:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:981:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [ [32m'E:\\pdf-tools-1.0.1\\pdf-tools-1.0.1\\cli.js'[39m ]
}
```
How can I solve it? Did I make a mistake in any step?
Thanks in advance.

**Comment by bsorrentino** [comment]
Hi @poorpaper 

1. Which version of `node` are you using ?
2. Did you have installed package globally (`-g`) ? 
3. Did you try to uninstall and install again ?

Let me know

**Comment by poorpaper** [comment]
Hello, @bsorrentino .Thanks for the reply,
1. node version is 16.16.0
2. I have installed package with the command `npm install ./pdf-tools -g`
3. I have uninstalled it with the command `npm remove ./pdf-tools -g` and reinstalled with `npm install ./pdf-tools -g`, after I run `pdftools pdf2md` it shows the same error.
I'm sorry that I'm not familiar with node.js.

**Comment by bsorrentino** [comment]
Hi @poorpaper no problem 

**remove all** and try 

```
npm install @bsorrentino/pdf-tools -g
```

and let me know

**Comment by poorpaper** [comment]
Thank you @bsorrentino , I have tried that command and it works!
But it shows the information below after I run the command `pdftools pdf2md E:\test\Docker.pdf -o E:\test\output` :
```
monospace or code font doesn't exists!
monospace or code font doesn't exists!
monospace or code font doesn't exists!
monospace or code font doesn't exists!
monospace or code font doesn't exists!
monospace or code font doesn't exists!
WARN: file Docker\Docker.fonts.json already exists!
```
The document contains Chinese, is this the cause of the error?

**Comment by bsorrentino** [comment]
Hi @poorpaper that's normal

the font mapping is your responsibility for this reason the tool generates the `Docker.fonts.json` file

message `monospace or code font doesn't exists!` means that tool has detected code block but doesn't find the font mapping.

However now it works! 👍🏻
