### ISSUE TITLE
page separator

### ISSUE THREAD

**Issue by hubschne** [bsorrentino/extract-pdf-images#6]
Hello,
I want to change my pdf slides to a markdown-based slide design and have discovered your great tool for this. It would be very helpful for me to add a separator in the markdown between the slides (pages) to be able to easily tell the slides apart.
I would be very happy if you could include it (eg a blank line between slides) or if you could give me a tip on how to include it in your project (the part of the code that I would have to change).
Thank you for your tool and thank you in advance for your help.

**Comment by bsorrentino** [comment]
Hi @hubschne thank you for using this tool. 

Could you provide me a sample PDF with your expected Markdown result ? This would help me a lot to be effective in solving this issue.

**Comment by hubschne** [comment]
Hey @bsorrentino,
thanks for your fast reply :) 

This is the [Example_Presentation.pdf](https://github.com/bsorrentino/pdf-tools/files/11517678/Example_Presentation.pdf), which results with your tool in this markdown file: 
[Example_Presentation.md](https://github.com/bsorrentino/pdf-tools/files/11517706/Example_Presentation.md)

What I would love to have, is a separator for example "---" to indicate the end of a slide. The output could look like this: 
[Example_Presentation_with_separator.md](https://github.com/bsorrentino/pdf-tools/files/11517699/Example_Presentation_with_separator.md)

Thanks for your help :)

**Comment by bsorrentino** [comment]
Feature released in version `1.1.0`

**Comment by bsorrentino** [comment]
Hi @hubschne I solved your problem take a look to readme I've added a new option `--pageseparator`

**Comment by hubschne** [comment]
Thank you for your entire project and your efforts to enhance your tool so quickly! 💐 That will help me a lot :)
