### ISSUE TITLE
Output Directory option doesn't work

### ISSUE THREAD

**Issue by TechQuery** [bsorrentino/extract-pdf-images#8]
```sh
pdftools -o ./custom-folder pdf2md some-document.pdf
```
@bsorrentino no `custom-folder` created after this command run.

**Comment by bsorrentino** [comment]
Hi @TechQuery thanks for feedback

I'll check asap

**Comment by bsorrentino** [comment]
Hi @TechQuery 

There was an error on `commander`  option inheritance, I've fixed problem and I'll arrange a new release soon

**Usage must be**
> `pdftools  pdf2md some-document.pdf -o ./custom-folder`

**Comment by bsorrentino** [comment]
fix published on release `1.2.1`
